In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3,4]
print(lst)

[1, 2, 3, 4]


In [3]:
print('1D array')
a = np.array([1,2,3,4,5])
print(a)

1D array
[1 2 3 4 5]


In [8]:
print('2D array')
b = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])
print(b)

2D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
print('3D array')
c = np.array([[[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15]]])
               
print(c)

3D array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [10]:
type(a)

numpy.ndarray

In [11]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [12]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [13]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [16]:
d = np.array([[1,2,3,4.2,5],
               [6,7,8.9,9,10],
               [11,12,13,14,15]])
print(d.dtype)

float64


In [17]:
d.transpose()

array([[ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8.9, 13. ],
       [ 4.2,  9. , 14. ],
       [ 5. , 10. , 15. ]])